### ISSUE TITLE
Reconnect websocket

### ISSUE THREAD

**Issue by wannesdemaeght** [HyperCubeProject/binance-api-node#24]
Sometimes the websocket stops receiving data, or times out.

Would it be possible to give us an easy way to disconnect, and afterwards reconnect, the existing socket?

**Comment by balthazar** [comment]
Related to #13. 

So right now you can disconnect easily by calling the function returned by the websocket call as showed in the docs. As discussed in the linked issue, maybe providing a callback to the method when a socket disconnect like `onClose` would allow you to redo the connection, what do you think?

**Comment by wannesdemaeght** [comment]
decided not to wait for the onDisconnect, as websockets sometimes have a tendency to stay connected far longer than they're emitting data...

I now check for the Nonce, and if it hasn't changed in 10 seconds, that woul be the cue to restart the websocket.

Will take a look at the docs again ;-)

**Comment by wannesdemaeght** [comment]
Alright, Clean() works great.
Is there an easy way to restart the configured websocket, without having to duplicate the instructions?

**Comment by wannesdemaeght** [comment]
This is my code:

const Binance_Websocket = Binance_WS.ws.ticker(Market.Binance.slice(1), ticker => {
		for (x = 1; x < NumberOfAlts+1; x++) {	
			if (ticker.symbol == Market.Binance[x]) {
				Price.Ask.Binance[x] 	= ticker.bestAsk;
				Ticker.New.Binance[x]	= ticker.eventTime;
			}
		}
	})




For ending the websocket, I use Binance_Websocket().
How could I then restart it easily?

**Comment by balthazar** [comment]
Yeah I think I might implement a way to pass a reconnect flag or something that would clean + reopen all connections (in case the user has passed multiple tickers for example)

**Comment by wannesdemaeght** [comment]
That would be awesome, because I actually pass an array of markets to the ticker websocket.

**Comment by nmarquesb** [comment]
In fact, it would be great to return websocket itself. Then, it would be possible to control state/close or even add some logic on close even.
But for now, a reconnect flag would be awesome. If you need, i can help.

**Comment by jshkurti** [comment]
Hello fellow duoquadragintien @balthazar ;-)

Could we do something like this ?

```javascript
const depth = (payload, cb, onclose) => {
  const cache = (Array.isArray(payload) ? payload : [payload]).forEach(symbol => {
    const w = new WebSocket(`${BASE}/${symbol.toLowerCase()}@depth`)
    w.onclose = onclose;
    w.on('message', msg => {
      const {
        e: eventType,
        E: eventTime,
        s: symbol,
        u: updateId,
        b: bidDepth,
        a: askDepth,
      } = JSON.parse(msg)

      cb({
        eventType,
        eventTime,
        symbol,
        updateId,
        bidDepth: bidDepth.map(b => zip(['price', 'quantity'], b)),
        askDepth: askDepth.map(a => zip(['price', 'quantity'], a)),
      })
    })
  })

  return () => cache.forEach(w => {
    w.onclose = undefined; // user manually cleaned the socket, don't call the custom onclose method
    w.close()
  })
}
```

And then use it : 

```javascript
let cleanDepthWs = client.ws.depth('ETHBTC', function depthListener(depth) {
  console.log(depth)
}, function onclose() {
  // one or more sockets were closed, do what you want
  cleanDepthWs();
  cleanDepthWs = client.ws.depth('ETHBTC', depthListener, onclose); // reconnect
})
```

`onclose` being undefined does nothing so it won't break the API if we don't pass a onclose callback at all :)

**Comment by balthazar** [comment]
I'm thinking of something a bit more customizable, I have a local branch doing some testing right now, will publish and ask for feedback here once it's close to ready

**Comment by danielkalen** [comment]
Maybe consider using an external module for handling auto-reconnects like [this lib](https://github.com/zcong1993/node-reconnect-ws)?

**Comment by danielkalen** [comment]
Or maybe we can attach the websocket object as a property of the returned close function so that users can directly listen for error/close events on the websocket and handle reconnection by themselves? Something along the likes of this:
```javascript
var close = client.ws.depth(...);
close.ws.on('error', (err) => ...)
```

**Comment by balthazar** [comment]
It's not as simple as that, since you can open multiple sockets in one go as I already said 🙂

**Comment by danielkalen** [comment]
I see... So that leaves only a few options that we can implement for this, and since I'm guessing that you don't want to break the existing api we have to figure a way to implement a solution on top of the current callback-returning api. We can:

1) expose the ws cache *array* as a property on the returned callback so that users can attach event listeners and handle reconnection by themselves.
2) handle reconnection internally and abstract error handling from the users entirely.

At first I thought the 2nd option will require an introduction of an options object to control the reconnect interval, max reconnects, etc. but after some thought I realized that when users of the lib open a websocket they'd only be interested in the data coming through and would want data to keep coming in until the moment that they are no longer interested in it and close the socket. This means that in most scenarios if there is a problem with the connection the user would want the socket to keep reconnecting until they explicitly tell it to stop. I think this option will make more sense as the first option will lead to a horrible api and since most users would want a reconnecting ws everywhere there will be a lot of code repetition.

I think that implementing reconnection internally with a sane reconnection delay would make most sense here

**Comment by danielkalen** [comment]
I created another pull request https://github.com/HyperCubeProject/binance-api-node/pull/40 on top of https://github.com/HyperCubeProject/binance-api-node/pull/38 which I created only handles reconnecting on `error` events but after using that branch in production env I quickly realized that there are many cases in which the connection gets disconnected for whatever reason and doesn't emit an `error` event but rather just a `close` event. This new pr is modified to handle these close events and also distinguishes between a user-invoked close event and a non-user-invoked closed event.

**Comment by Ekliptor** [comment]
When you add reconnect + error handler, please also fix this crash related to it. Currently it throughs an uncaught exception (which crashes a nodejs app) when connecting failed.

Running this code without internet connection
```
const clean = client.ws.depth('ETHBTC', depth => {
  console.log(depth)
})
```

Will give you:
```Uncaught Exception
Error: getaddrinfo ENOTFOUND stream.binance.com stream.binance.com:9443
at errnoException (dns.js:55:10)
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:26)
```

There is no way to catch this error, since its stacktrace is internal (missing error handlers in your library).

**Comment by bennyn** [comment]
@balthazar I am also concerned about expiring WebSocket connections. 

What I can recommend is using a npm package that handles WebSocket reconnection out-of-the box. I made very good experiences with [reconnecting-websocket](https://github.com/pladaria/reconnecting-websocket). All we need to do is using that WebSocket wrapper and we are good. 🌞 

Here is a reference integration:
- https://github.com/wireapp/wire-web-packages/blob/%40wireapp/store-engine%400.1.13/packages/api-client/src/main/tcp/WebSocketClient.ts#L25

**Comment by balthazar** [comment]
Reconnecting WebSockets have been added since `0.7.0`, thanks @bennyn!

**Comment by numerized** [comment]
It has been few days that I experience again socket disconnections.
I am on 

"binance-api-node": "^0.8.4"

Here's my code basically it works few hours and then nothing no more msg from the socket.

`// STARTING USER MESSAGING SOCKETS
startUserMsgSocket = () => {

	userMsgSocket = client.ws.user(msg => {

		// we update live wallet on receiving account eventType
		if(msg.eventType == 'account') {
			updateLiveWallet(msg.balances);
		}
}
`
